/* "Copyright 2018 Alexander Colon" */
#ifndef ASSIGNMENT_2_LEARN_GITHUB_AFCOLON_INCLUDE_HELLOMAKE_H_
#define ASSIGNMENT_2_LEARN_GITHUB_AFCOLON_INCLUDE_HELLOMAKE_H_

void myPrintHelloMake(void);

#endif  // ASSIGNMENT_2_LEARN_GITHUB_AFCOLON_INCLUDE_HELLOMAKE_H_
